ViLearning/Models/Question.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ViLearning.Models
{
    public enum Difficulty
    {
        Easy,
        Medium,
        Hard
    }

    public enum QuestionType
    {
        MultipleChoice,
        Essay
    }
    public class Question
    {
        [Key]
        public int QuestionId { get; set; }
        public string QuestionName { get; set; }
        public string? OptionA { get; set; }
        public string? OptionB { get; set; }
        public string? OptionC { get; set; }
        public string? OptionD { get; set; }
        public string RightAnswer { get; set; }

        public QuestionType QuestionType { get; set; }
        public Difficulty Difficulty { get; set; }

        //Foreign key
        public int LessonId { get; set; }

        //Relation
        [ForeignKey("LessonId")]
        [ValidateNever]
        public Lesson Lesson { get; set; }
    }
}

ViLearning/Areas/Teacher/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ViLearning.Services.Repository.IRepository;
using ViLearning.Utility;
using System.Security.Claims;
using ViLearning.Models;
using ViLearning.Models.ViewModels;


namespace ViLearning.Areas.Teacher.Controllers
{
    [Area("Teacher")]
    [Authorize(Roles = SD.Role_User_Teacher)]
    public class QuestionController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public QuestionController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ViewUploadQuestionsFile(int courseId)
        {
            ViewData["courseId"] = courseId;
            Course course = _unitOfWork.Course.Get(c => c.CourseId == courseId);
            _unitOfWork.Course.LoadCourse(course);
            ViewData["lessonList"] = course.Lesson.ToList();
            return View("CourseQuestionBank");
        }

        [HttpPost]
        public async Task<IActionResult> UploadQuestions(int courseId, IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                return BadRequest("No file uploaded.");
            }

            var questions = new List<Question>();
            using (var stream = new StreamReader(file.OpenReadStream()))
            {
                Question question = null;
                while (!stream.EndOfStream)
                {
                    var line = await stream.ReadLineAsync();
                    if (string.IsNullOrWhiteSpace(line))
                    {
                        if (question != null)
                        {
                            questions.Add(question);
                            question = null;
                        }
                        continue;
                    }

                    if (question == null)
                    {
                        var parts = line.Split(',');
                        if (parts.Length < 3)
                        {
                            // Handle invalid line format
                            TempData["invalid-file-format"] = "File của bạn không đúng định dạng yêu cầu!";
                            return RedirectToAction("ViewUploadQuestionsFile", new { courseId = courseId });
                        }
                        // Check if lessonNo in the file is valid.
                        var lesson = _unitOfWork.Lesson.Get(l => l.CourseId == courseId && l.LessonNo == int.Parse(parts[0]));
                        if (lesson == null)
                        {
                            // Skip this question if the lesson is not found
                            while (!stream.EndOfStream && !string.IsNullOrWhiteSpace(line))
                            {
                                line = await stream.ReadLineAsync();
                            }
                            continue;
                        }

                        question = new Question
                        {
                            LessonId = _unitOfWork.Lesson.Get(l => l.CourseId == courseId && l.LessonNo == int.Parse(parts[0])).LessonId,
                            QuestionType = Enum.Parse<QuestionType>(parts[1]),
                            Difficulty = Enum.Parse<Difficulty>(parts[2])
                        };
                        line = await stream.ReadLineAsync();
                        question.QuestionName = line;
                    }
                    else
                    {
                        if (line.StartsWith("A."))
                        {
                            question.OptionA = line.Substring(2).Trim();
                        }
                        else if (line.StartsWith("B."))
                        {
                            question.OptionB = line.Substring(2).Trim();
                        }
                        else if (line.StartsWith("C."))
                        {
                            question.OptionC = line.Substring(2).Trim();
                        }
                        else if (line.StartsWith("D."))
                        {
                            question.OptionD = line.Substring(2).Trim();
                        }
                        else if (line.StartsWith("Correct:"))
                        {
                            question.RightAnswer = line.Substring(8).Trim();
                        }
                    }
                }

                if (question != null)
                {
                    questions.Add(question);
                }
            }

            _unitOfWork.Question.AddRange(questions);
            _unitOfWork.Save();
            TempData["upload-file-success"] = "Ngân hàng câu hỏi đã được cập nhật, ấn vào các bài học để xem";
            return RedirectToAction("ViewUploadQuestionsFile", new { courseId = courseId });
        }

        public async Task<IActionResult> QuestionManage(int lessonId)
        {
            QuestionManageVM vm = new QuestionManageVM();
            vm.Questions = await _unitOfWork.Question.GetQuestionByLessonId(lessonId);
            vm.Lesson = _unitOfWork.Lesson.Get(l => l.LessonId == lessonId, includeProperties: "Course");
           
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Add(QuestionManageVM vm)
        {
            if (vm.Question.QuestionType == QuestionType.Essay) 
                vm.Question.RightAnswer = "";
            _unitOfWork.Question.Add(vm.Question);
            _unitOfWork.Save();
            int lessonId = vm.Question.LessonId;

            return RedirectToAction("QuestionManage", new { lessonId = lessonId });
        }

        [HttpPost]
        public async Task<IActionResult> Update(QuestionManageVM vm)
        {
            if (vm.Question.QuestionType == QuestionType.Essay) 
                vm.Question.RightAnswer = "";
            _unitOfWork.Question.Update(vm.Question);
            _unitOfWork.Save();
            int lessonId = vm.Question.LessonId;

            return RedirectToAction("QuestionManage", new { lessonId = lessonId });
        }

        public async Task<IActionResult> Delete(int questionId)
        {
            Question question = _unitOfWork.Question.Get(q => q.QuestionId == questionId);
            Lesson lesson = _unitOfWork.Lesson.Get(l => l.LessonId == question.LessonId);
            _unitOfWork.Question.Remove(question);
            _unitOfWork.Save();
            

            return RedirectToAction("QuestionManage", new { lessonId = lesson.LessonId });
        }

        [HttpGet]
        public async Task<IActionResult> Search(QuestionManageVM vm)
        {
            if (vm.SearchString == null) vm.SearchString = "";
            vm.Questions = _unitOfWork.Question.GetRange(q => q.LessonId == vm.Question.LessonId && q.QuestionName.Contains(vm.SearchString))
                .OrderBy(x => x.Difficulty).ThenBy(x => x.LessonId).ToList();
            vm.Lesson = _unitOfWork.Lesson.Get(l => l.LessonId == vm.Question.LessonId, includeProperties: "Course");

            return View("QuestionManage",vm);
        }
    }
}

ViLearning/Areas/Teacher/Views/Question/CourseQuestionBank.cshtml
@{
    ViewData["Title"] = "Upload Questions";
    var items = ViewData["lessonList"] as List<Lesson>;
}

@section Styles {
<style>
        .lesson-no {
            font-weight: bold;
            color: #28a745;
        }

        .lesson-name {
            color: #343a40;
        }

        .list ul {
            position: relative;
        }

        .list ul li {
            position: relative;
            left: 0;
            color: #fce4ec;
            list-style: none;
            margin: 4px 0;
            border-left: 2px solid #28a745;
            transition: 0.5s;
            cursor: pointer;
        }

        .list ul li:hover {
            left: 10px;
        }

        .list ul li span {
            position: relative;
            padding: 8px;
            padding-left: 12px;
            display: inline-block;
            z-index: 1;
            transition: 0.5s;
        }

        .list ul li:hover span {
            color: white;
        }

        .list ul li:before {
            content: "";
            position: absolute;
            width: 100%;
            height: 100%;
            background: #28a745;
            transform: scaleX(0);
            transform-origin: left;
            transition: 0.5s;
        }

        .list ul li:hover:before {
            transform: scaleX(1);
        }
</style>
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">
            Upload Question File <i type="button" id="info-popover" data-bs-html="true" class="btn bi bi-info-circle" data-toggle="popover" data-bs-placement="bottom"
                                    title="<h5>Thêm câu hỏi hàng loạt</h5>"
                                    data-bs-content="Đây là cách để bạn có thể thêm câu hỏi hàng loạt vào ngân hàng câu hỏi của khóa học.<br>
                                              Hãy thêm file văn bản chứa các câu hỏi theo định dạng quy định của chúng tôi (nằm ở bên phải phần thêm file)."></i>
        </h3>
    </div>
    <div class="card-body row">
        <form class="col-md-6" method="post" enctype="multipart/form-data" id="uploadQuestionsForm" asp-area="Teacher" asp-controller="Question" asp-action="UploadQuestions">
            <div class="form-group">
                <input type="hidden" class="form-control" name="courseId" value="@ViewData["courseId"]"/>
                <label for="file">Upload Questions File</label>
                <input type="file" class="form-control" id="file" name="file" required>
            </div>
            <div id="UploadFile_ErrorMessage" class="alert alert-danger d-none error-message">Please select a file to upload.</div>
            <button type="submit" class="btn btn-primary">Upload</button>
            @if (TempData["invalid-file-format"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @TempData["invalid-file-format"]
                </div>
            }
            @if (TempData["upload-file-success"] != null)
            {
                <div class="alert alert-success" role="alert">
                    @TempData["upload-file-success"]
                </div>
            }
        </form>
        <div class="col-md-6">
            <h3>File Format</h3>
            <a class="question-file-format" data-gall="gallery01" href="~/images/question-file-format.png"><img width="600px" height="auto" src="~/images/question-file-format.png"></a>
        </div>
    </div>
</div>

<div class="container mt-4 list">
    <h2 class="mb-4">Danh sách các bài học</h2>
    @if (items != null && items.Any())
    {
        <ul class="list-group list-group-flush">
            @foreach (var item in items)
            {
                <li class="list-group-item d-flex justify-content-md-start align-items-center fs-4">
                    <a class="text-decoration-none" asp-area="Teacher" asp-controller="Question" asp-action="QuestionManage" asp-route-lessonId="@item.LessonId">
                        <span class="lesson-no me-3">@item.LessonNo.</span>
                        <span class="lesson-name">@item.LessonName</span>
                    </a>
                </li>
            }
        </ul>
    }
    else
    {
        <p>Không có bài học nào được tìm thấy.</p>
    }
</div>




@section Scripts {
    <script>
        $(function () {
            $('[data-toggle="popover"]').popover()
        })

        new VenoBox({
            selector: '.question-file-format',
            numeration: true,
            infinigall: true,
            share: true,
            spinner: 'rotating-plane'
        });
    </script>

}